// <auto-generated />
using System;
using MadinahPlus.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MadinahPlus.DataAccess.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818213809_BirzeitCivicRefresh")]
    partial class BirzeitCivicRefresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MadinahPlus.Domain.Entities.Business", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Certified")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.BusinessCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Met")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("business_criteria", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.CityDimension", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CertifiedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CityProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Sparkline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<int>("Trend")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CityProfileId");

                    b.ToTable("city_dimensions", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.CityProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("MapCenterLat")
                        .HasColumnType("double precision");

                    b.Property<double>("MapCenterLng")
                        .HasColumnType("double precision");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("city_profiles", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.FeedbackCategory", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Key");

                    b.ToTable("feedback_categories", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.HousingFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HousingUnitId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HousingUnitId");

                    b.ToTable("housing_facilities", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.HousingUnit", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly?>("CertifiedDate")
                        .HasColumnType("date");

                    b.Property<bool>("ConditionalIssued")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastInspection")
                        .HasColumnType("date");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("housing_units", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.ImprovementPriority", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("improvement_priorities", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.InspectionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HousingUnitId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HousingUnitId");

                    b.ToTable("inspection_categories", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.InspectionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InspectionCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InspectionCategoryId");

                    b.ToTable("inspection_items", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.MonitoringMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("After")
                        .HasColumnType("integer");

                    b.Property<int>("Before")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("monitoring_metrics", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.RouteCriterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Met")
                        .HasColumnType("boolean");

                    b.Property<string>("SafeRouteId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SafeRouteId");

                    b.ToTable("route_criteria", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("SafeRouteId")
                        .IsRequired()
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SafeRouteId");

                    b.ToTable("route_points", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.SafeRoute", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("safe_routes", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.StudentFeedback", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CategoryKey")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CategoryKey");

                    b.ToTable("student_feedback", (string)null);
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.Business", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Category", b1 =>
                        {
                            b1.Property<string>("BusinessId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("category_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("category_en");

                            b1.HasKey("BusinessId");

                            b1.ToTable("businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("BusinessId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_en");

                            b1.HasKey("BusinessId");

                            b1.ToTable("businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.BusinessCriterion", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.Business", "Business")
                        .WithMany("Criteria")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("BusinessCriterionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("BusinessCriterionId");

                            b1.ToTable("business_criteria");

                            b1.WithOwner()
                                .HasForeignKey("BusinessCriterionId");
                        });

                    b.Navigation("Business");

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.CityDimension", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.CityProfile", "CityProfile")
                        .WithMany("Dimensions")
                        .HasForeignKey("CityProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("CityDimensionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("CityDimensionId");

                            b1.ToTable("city_dimensions");

                            b1.WithOwner()
                                .HasForeignKey("CityDimensionId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Problems", b1 =>
                        {
                            b1.Property<int>("CityDimensionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("problems_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("problems_en");

                            b1.HasKey("CityDimensionId");

                            b1.ToTable("city_dimensions");

                            b1.WithOwner()
                                .HasForeignKey("CityDimensionId");
                        });

                    b.Navigation("CityProfile");

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("Problems")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.CityProfile", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("CityProfileId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_en");

                            b1.HasKey("CityProfileId");

                            b1.ToTable("city_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CityProfileId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Tagline", b1 =>
                        {
                            b1.Property<int>("CityProfileId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("tagline_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("tagline_en");

                            b1.HasKey("CityProfileId");

                            b1.ToTable("city_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CityProfileId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Tagline")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.FeedbackCategory", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<string>("FeedbackCategoryKey")
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("FeedbackCategoryKey");

                            b1.ToTable("feedback_categories");

                            b1.WithOwner()
                                .HasForeignKey("FeedbackCategoryKey");
                        });

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.HousingFacility", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.HousingUnit", "HousingUnit")
                        .WithMany("Facilities")
                        .HasForeignKey("HousingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<int>("HousingFacilityId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_en");

                            b1.HasKey("HousingFacilityId");

                            b1.ToTable("housing_facilities");

                            b1.WithOwner()
                                .HasForeignKey("HousingFacilityId");
                        });

                    b.Navigation("HousingUnit");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.HousingUnit", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Distance", b1 =>
                        {
                            b1.Property<string>("HousingUnitId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("distance_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("distance_en");

                            b1.HasKey("HousingUnitId");

                            b1.ToTable("housing_units");

                            b1.WithOwner()
                                .HasForeignKey("HousingUnitId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("HousingUnitId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_en");

                            b1.HasKey("HousingUnitId");

                            b1.ToTable("housing_units");

                            b1.WithOwner()
                                .HasForeignKey("HousingUnitId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Price", b1 =>
                        {
                            b1.Property<string>("HousingUnitId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("price_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("price_en");

                            b1.HasKey("HousingUnitId");

                            b1.ToTable("housing_units");

                            b1.WithOwner()
                                .HasForeignKey("HousingUnitId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Provider", b1 =>
                        {
                            b1.Property<string>("HousingUnitId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("provider_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("provider_en");

                            b1.HasKey("HousingUnitId");

                            b1.ToTable("housing_units");

                            b1.WithOwner()
                                .HasForeignKey("HousingUnitId");
                        });

                    b.Navigation("Distance")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Provider")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.ImprovementPriority", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Action", b1 =>
                        {
                            b1.Property<string>("ImprovementPriorityId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("action_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("action_en");

                            b1.HasKey("ImprovementPriorityId");

                            b1.ToTable("improvement_priorities");

                            b1.WithOwner()
                                .HasForeignKey("ImprovementPriorityId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Impact", b1 =>
                        {
                            b1.Property<string>("ImprovementPriorityId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("impact_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("impact_en");

                            b1.HasKey("ImprovementPriorityId");

                            b1.ToTable("improvement_priorities");

                            b1.WithOwner()
                                .HasForeignKey("ImprovementPriorityId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<string>("ImprovementPriorityId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_en");

                            b1.HasKey("ImprovementPriorityId");

                            b1.ToTable("improvement_priorities");

                            b1.WithOwner()
                                .HasForeignKey("ImprovementPriorityId");
                        });

                    b.Navigation("Action")
                        .IsRequired();

                    b.Navigation("Impact")
                        .IsRequired();

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.InspectionCategory", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.HousingUnit", "HousingUnit")
                        .WithMany("Inspection")
                        .HasForeignKey("HousingUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("InspectionCategoryId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("InspectionCategoryId");

                            b1.ToTable("inspection_categories");

                            b1.WithOwner()
                                .HasForeignKey("InspectionCategoryId");
                        });

                    b.Navigation("HousingUnit");

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.InspectionItem", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.InspectionCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("InspectionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("InspectionItemId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("InspectionItemId");

                            b1.ToTable("inspection_items");

                            b1.WithOwner()
                                .HasForeignKey("InspectionItemId");
                        });

                    b.Navigation("Category");

                    b.Navigation("Label")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.RouteCriterion", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.SafeRoute", "SafeRoute")
                        .WithMany("Criteria")
                        .HasForeignKey("SafeRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<int>("RouteCriterionId")
                                .HasColumnType("integer");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("RouteCriterionId");

                            b1.ToTable("route_criteria");

                            b1.WithOwner()
                                .HasForeignKey("RouteCriterionId");
                        });

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("SafeRoute");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.RoutePoint", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.SafeRoute", "SafeRoute")
                        .WithMany("Path")
                        .HasForeignKey("SafeRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SafeRoute");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.SafeRoute", b =>
                {
                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "From", b1 =>
                        {
                            b1.Property<string>("SafeRouteId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("from_point_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("from_point_en");

                            b1.HasKey("SafeRouteId");

                            b1.ToTable("safe_routes");

                            b1.WithOwner()
                                .HasForeignKey("SafeRouteId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Label", b1 =>
                        {
                            b1.Property<string>("SafeRouteId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("label_en");

                            b1.HasKey("SafeRouteId");

                            b1.ToTable("safe_routes");

                            b1.WithOwner()
                                .HasForeignKey("SafeRouteId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Name", b1 =>
                        {
                            b1.Property<string>("SafeRouteId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("name_en");

                            b1.HasKey("SafeRouteId");

                            b1.ToTable("safe_routes");

                            b1.WithOwner()
                                .HasForeignKey("SafeRouteId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "To", b1 =>
                        {
                            b1.Property<string>("SafeRouteId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("to_point_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("to_point_en");

                            b1.HasKey("SafeRouteId");

                            b1.ToTable("safe_routes");

                            b1.WithOwner()
                                .HasForeignKey("SafeRouteId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Via", b1 =>
                        {
                            b1.Property<string>("SafeRouteId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("via_point_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("via_point_en");

                            b1.HasKey("SafeRouteId");

                            b1.ToTable("safe_routes");

                            b1.WithOwner()
                                .HasForeignKey("SafeRouteId");
                        });

                    b.Navigation("From")
                        .IsRequired();

                    b.Navigation("Label")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("To")
                        .IsRequired();

                    b.Navigation("Via")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.StudentFeedback", b =>
                {
                    b.HasOne("MadinahPlus.Domain.Entities.FeedbackCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "LinkedTo", b1 =>
                        {
                            b1.Property<string>("StudentFeedbackId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("linked_to_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("linked_to_en");

                            b1.HasKey("StudentFeedbackId");

                            b1.ToTable("student_feedback");

                            b1.WithOwner()
                                .HasForeignKey("StudentFeedbackId");
                        });

                    b.OwnsOne("MadinahPlus.Domain.ValueObjects.LocalizedText", "Text", b1 =>
                        {
                            b1.Property<string>("StudentFeedbackId")
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Ar")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_ar");

                            b1.Property<string>("En")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("text_en");

                            b1.HasKey("StudentFeedbackId");

                            b1.ToTable("student_feedback");

                            b1.WithOwner()
                                .HasForeignKey("StudentFeedbackId");
                        });

                    b.Navigation("Category");

                    b.Navigation("LinkedTo")
                        .IsRequired();

                    b.Navigation("Text")
                        .IsRequired();
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.Business", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.CityProfile", b =>
                {
                    b.Navigation("Dimensions");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.HousingUnit", b =>
                {
                    b.Navigation("Facilities");

                    b.Navigation("Inspection");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.InspectionCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MadinahPlus.Domain.Entities.SafeRoute", b =>
                {
                    b.Navigation("Criteria");

                    b.Navigation("Path");
                });
#pragma warning restore 612, 618
        }
    }
}
